language: android
sudo: false
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.1
    - android-26
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
script:
- "./gradlew --stacktrace check jacocoReport"
after_success:
- bash <(curl -s https://codecov.io/bash)
