language: android
sudo: false
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-24
    - extra-android-support
    - extra-android-m2repository
script:
- "./gradlew build jacocoTestReport"
after_success:
- bash <(curl -s https://codecov.io/bash)